language: generic

services:
  - docker

before_install:
  - docker build -t andrewbalzer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrewbalzer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-638589730730"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
