language: node_js
node_js:
  - 7

services:
  - docker

before_install:
  - docker build -t andrewbalzer/docker-react -f Dockerfile.dev .

script:
  - docker run andrewbalzer/docker-react npm run test -- --coverage
